### ISSUE TITLE
Use a mock for tests

### ISSUE THREAD

**Issue by pengux** [jonboydell/logzio_client#39]
Currently, the tests seem to require a valid API token and is actually making requests against the Logz.io API. This makes it non-trivial to contribute to the project as it requires to have an Enterprise account just for running the tests. I suggest to use a mock for the tests and complement with integration tests which can do real requests against the API if desired.

**Comment by jonboydell** [comment]
development branch for introducing mocks for testing - release_1_2_mocks

**Comment by jonboydell** [comment]
@pengux - agree - which functions would you mock?  the ones that make the API HTTP calls?  or some higher level of abstraction?

**Comment by pengux** [comment]
@jonboydell The whole API can be mocked with a simple HTTP server and `httptest` which just return fixed test data. The mock can be set to expect a specific request and return the appropriate response for it. This way, the one writing the test can for example inject invalid/valid responses to test against.

**Comment by jonboydell** [comment]
thanks @pengux - i thought you meant a mock as in https://github.com/golang/mock - i'm not au fait with `httptest` will look into it

**Comment by pengux** [comment]
@jonboydell I think something like https://github.com/jarcoal/httpmock is more suitable for mocking APIs

**Comment by jonboydell** [comment]
@pengux - didn't see that till just now, have already implemented httptest across the Users part of the lib - going to stick with that for Users but might use the other lib for Endpoints and Alerts and then upgrade - BTW - I am jonboydell@hotmail.com - I'd prefer email over Slack ATM, if it doesn't work we can use Slack, but unless you pay for it, it deletes the chat history after 24 hours :(

**Comment by jonboydell** [comment]
framework is now in develop, so closing this issue - improvements to test coverage to be tracked as individual issues...
