### ISSUE TITLE
Use go modules

### ISSUE THREAD

**Issue by pengux** [jonboydell/logzio_client#40]
[Go modules](https://github.com/golang/go/wiki/Modules) has become the canonical way to handle dependencies in a Go project. I would be happy to add support for Go modules in this project.

**Comment by jonboydell** [comment]
going to add you as a collaborator

**Comment by jonboydell** [comment]
what's the best way for us to communicate?  GH issues doesn't seem like the right place :)

**Comment by pengux** [comment]
@jonboydell How about Slack, IRC, email or what are convenient for you?

**Comment by jonboydell** [comment]
I am jonboydell@hotmail.com - I'd prefer email over Slack ATM, if it doesn't work we can use Slack, but unless you pay for it, it deletes the chat history after 24 hours :(
